'use client';

export const quizData = [
  // MODULE 0: INFORMATIQUE (ORDINATEUR) - 30 Questions
  {
    id: 0,
    module: 'IT (Ordinateur)',
    time: null,
    description: 'Module informatique de base (30 questions)',
    questions: [
      {
        id: 1,
        text: 'Lequel de ces éléments est un périphérique de sortie (qui affiche ou communique des données) ?',
        options: ['Clavier', 'Souris', 'Écran d\'affichage', 'Microphone'],
        correct: 2,
        explanation: 'Un périphérique de sortie envoie des informations de l\'ordinateur vers l\'utilisateur. L\'écran affiche les données. Le clavier, la souris et le microphone sont des périphériques d\'entrée : ils envoient des données vers l\'ordinateur.',
      },
      {
        id: 2,
        text: 'À quoi sert la mémoire vive (RAM) dans un ordinateur ?',
        options: [
          'Stocker définitivement vos fichiers',
          'Permettre au processeur d\'accéder rapidement aux données en cours d\'utilisation',
          'Recharger la batterie',
          'Afficher les images sur l\'écran',
        ],
        correct: 1,
        explanation: 'La RAM (Random Access Memory) est une mémoire temporaire et rapide. Elle stocke les données que le processeur utilise en ce moment. Quand vous éteignez l\'ordinateur, la RAM est vidée. Pour stocker durablement, on utilise le disque dur ou le SSD.',
      },
      {
        id: 3,
        text: 'Votre ordinateur est très lent et fait beaucoup de bruits. Quel est probablement le problème ?',
        options: [
          'Le clavier est cassé',
          'Vous avez trop de programmes ouverts ou le disque est presque plein',
          'C\'est normal, tous les ordinateurs sont lents',
          'L\'écran consomme trop d\'énergie',
        ],
        correct: 1,
        explanation: 'Un ordinateur lent avec du bruit indique souvent que le processeur ou le disque dur est surchargé. Trop de programmes ouverts consomment la RAM et forcent l\'ordinateur à utiliser davantage le disque. Un disque presque plein ralentit aussi tout le système.',
      },
      {
        id: 4,
        text: 'Quel système d\'exploitation n\'existe PAS ?',
        options: ['Windows (Microsoft)', 'Système macOS (Apple)', 'Linux (gratuit, accès source)', 'Chromesoft'],
        correct: 3,
        explanation: 'Les vrais systèmes d\'exploitation sont Windows (Microsoft), macOS (Apple) et Linux (open source). "Chromesoft" n\'existe pas. Il existe ChromeOS (de Google), mais "Chromesoft" est un nom inventé.',
      },
      {
        id: 5,
        text: 'Quel est le principal avantage d\'un disque SSD par rapport à un disque dur mécanique ?',
        options: [
          'Plus d\'espace de stockage disponible',
          'Plus rapide, plus silencieux, pas de pièces mobiles',
          'Moins cher à l\'achat',
          'Meilleur pour les jeux vidéo',
        ],
        correct: 1,
        explanation: 'Le SSD (Solid State Drive) utilise de la mémoire flash sans pièces mécaniques. Il démarre plus vite, lit et écrit les données plus rapidement, résiste mieux aux chocs et est silencieux. Le disque dur HDD est moins cher mais plus lent et fragile.',
      },
      {
        id: 6,
        text: 'Le processeur d\'un ordinateur est connu pour être le "cerveau" de l\'ordinateur. Pourquoi ?',
        options: [
          'Il stocke tous vos fichiers',
          'Il exécute toutes les instructions et contrôle les autres composants',
          'Il affiche les images sur l\'écran',
          'Il crée Internet',
        ],
        correct: 1,
        explanation: 'Le processeur (CPU) exécute les instructions des programmes, effectue les calculs et coordonne tous les composants. Comme un cerveau, il dirige les opérations. Il ne stocke pas les fichiers (c\'est le disque) ni n\'affiche les images (c\'est la carte graphique).',
      },
      {
        id: 7,
        text: 'Dans Windows, à quoi sert l\'explorateur de fichiers ?',
        options: [
          'À supprimer automatiquement les virus',
          'À naviguer dans la structure des dossiers et fichiers de votre ordinateur',
          'À télécharger Internet',
          'À changer la couleur de votre bureau',
        ],
        correct: 1,
        explanation: 'L\'explorateur de fichiers (aussi appelé "Poste de travail" ou "Ce PC") permet de naviguer dans les dossiers, copier, déplacer, renommer ou supprimer des fichiers. C\'est l\'outil principal pour gérer l\'organisation de vos données sur l\'ordinateur.',
      },
      {
        id: 8,
        text: 'Vous cliquez droit sur un fichier et sélectionnez "Propriétés". Quelle information pouvez-vous voir ?',
        options: [
          'Seulement le nom du fichier',
          'La taille, la date de création, le chemin d\'accès, le type de fichier',
          'Un accès direct à Internet',
          'Le mot de passe de votre ordinateur',
        ],
        correct: 1,
        explanation: 'La fenêtre "Propriétés" d\'un fichier affiche des informations détaillées : sa taille, son type (extension), son emplacement exact, la date de création et de dernière modification. C\'est très utile pour vérifier un fichier avant de l\'ouvrir ou de le partager.',
      },
      {
        id: 9,
        text: 'Comment libérer de l\'espace sur le disque dur de votre ordinateur ?',
        options: [
          'Éteindre l\'ordinateur plusieurs fois par jour',
          'Supprimer les fichiers inutiles, les anciens téléchargements, les fichiers temporaires',
          'Augmenter le volume des haut-parleurs',
          'Mettre à jour le système d\'exploitation',
        ],
        correct: 1,
        explanation: 'Pour libérer de l\'espace disque, supprimez les fichiers inutiles, videz la corbeille, nettoyez le dossier Téléchargements et utilisez l\'outil "Nettoyage de disque" de Windows pour supprimer les fichiers temporaires. Éteindre l\'ordinateur ou monter le volume n\'a aucun effet sur l\'espace disque.',
      },
      {
        id: 10,
        text: 'Lequel est un format de fichier image couramment utilisé ?',
        options: ['JPEG', 'DOCX', 'XLSX', 'MPEG'],
        correct: 0,
        explanation: 'JPEG (.jpg) est un format image très répandu, idéal pour les photos. DOCX est un document Word, XLSX est un tableur Excel, et MPEG est un format vidéo. Pour les images, on utilise aussi PNG (fond transparent), GIF (animations) et WebP (web moderne).',
      },
      {
        id: 11,
        text: 'Pourquoi est-il important d\'avoir un antivirus sur votre ordinateur ?',
        options: [
          'Pour accélérer Internet',
          'Pour protéger votre ordinateur contre les virus, logiciels malveillants et menaces informatiques',
          'Pour augmenter la taille du disque',
          'Pour changer le fond d\'écran',
        ],
        correct: 1,
        explanation: 'Un antivirus surveille en permanence les fichiers et les activités de l\'ordinateur pour détecter les virus, malwares, ransomwares et autres menaces. Sans antivirus, votre ordinateur peut être infecté via des téléchargements, clés USB ou sites web malveillants, compromettant vos données personnelles.',
      },
      {
        id: 12,
        text: 'Que fait une mise à jour système sur votre ordinateur ?',
        options: [
          'Rend votre ordinateur plus lent',
          'Corrige les failles de sécurité, ajoute des fonctionnalités, améliore la stabilité',
          'Supprime tous vos fichiers',
          'Change votre mot de passe automatiquement',
        ],
        correct: 1,
        explanation: 'Les mises à jour corrigent des vulnérabilités de sécurité découvertes après la sortie du système, améliorent les performances et ajoutent parfois de nouvelles fonctionnalités. Ne pas faire les mises à jour laisse votre ordinateur exposé à des failles connues que les hackers peuvent exploiter.',
      },
      {
        id: 13,
        text: 'À quoi sert un port USB sur un ordinateur ?',
        options: [
          'À chauffer l\'ordinateur',
          'À connecter des périphériques comme une souris, clé USB, imprimante, etc.',
          'À émettre Internet',
          'À afficher les images',
        ],
        correct: 1,
        explanation: 'USB (Universal Serial Bus) est un port universel permettant de connecter presque tous types de périphériques : clé USB, souris, clavier, imprimante, téléphone, disque externe. Il peut aussi fournir de l\'alimentation pour charger des appareils.',
      },
      {
        id: 14,
        text: 'Qu\'est-ce que le Wi-Fi sur un ordinateur ?',
        options: [
          'Un type de virus informatique',
          'Une technologie pour se connecter à Internet sans fil',
          'Un nom de processeur',
          'Un type de fichier à télécharger',
        ],
        correct: 1,
        explanation: 'Le Wi-Fi est une technologie de communication sans fil qui permet de connecter un ordinateur à un réseau local et à Internet sans câble. Il fonctionne via des ondes radio captées par une carte Wi-Fi et diffusées par un routeur ou une box Internet.',
      },
      {
        id: 15,
        text: 'Quelle est la différence entre un simple clic et un double clic de souris ?',
        options: [
          'Aucune différence',
          'Le simple clic sélectionne, le double clic ouvre généralement le fichier ou programme',
          'Le double clic est plus lent',
          'Le simple clic rend l\'ordinateur plus rapide',
        ],
        correct: 1,
        explanation: 'Un simple clic sélectionne un élément (le met en surbrillance). Un double clic l\'ouvre ou l\'exécute. Par exemple, un simple clic sur un fichier le sélectionne, mais un double clic l\'ouvre avec le logiciel associé. Sur Internet, un simple clic suffit souvent pour les liens.',
      },
      {
        id: 16,
        text: 'À quoi sert la barre des tâches au bas de votre écran Windows ?',
        options: [
          'À jouer de la musique',
          'À afficher les programmes ouverts, l\'heure, et permettre de lancer des programmes',
          'À afficher les images uniquement',
          'À charger les jeux vidéo',
        ],
        correct: 1,
        explanation: 'La barre des tâches est la barre horizontale en bas de l\'écran Windows. Elle contient le bouton Démarrer, les programmes épinglés, les fenêtres ouvertes, et la zone de notification (horloge, Wi-Fi, volume). Elle vous permet de passer rapidement d\'un programme à l\'autre.',
      },
      {
        id: 17,
        text: 'Quel est l\'avantage d\'avoir deux écrans connectés au même ordinateur ?',
        options: [
          'C\'est deux fois plus lent',
          'Augmente l\'espace de travail, améliore la productivité',
          'C\'est seulement pour les jeux vidéo',
          'Cela rend l\'ordinateur cassé',
        ],
        correct: 1,
        explanation: 'Un double écran (configuration multi-moniteurs) permet d\'étendre le bureau sur deux surfaces : vous pouvez avoir un document sur un écran et votre messagerie sur l\'autre, ou comparer deux fichiers côte à côte. C\'est très courant dans les entreprises pour améliorer la productivité.',
      },
      {
        id: 18,
        text: 'Pourquoi la batterie d\'un ordinateur portable se décharge avec le temps ?',
        options: [
          'Le disque dur consomme toute l\'électricité',
          'Les composants de l\'ordinateur consomment l\'énergie stockée dans la batterie',
          'Parce que vous oubliez d\'éteindre l\'ordinateur',
          'La batterie devient automatiquement cassée',
        ],
        correct: 1,
        explanation: 'L\'ordinateur portable utilise l\'énergie de sa batterie pour alimenter le processeur, l\'écran, la RAM, le Wi-Fi et tous ses composants. Plus vous utilisez l\'ordinateur intensément (jeux, vidéos), plus la consommation est rapide. La batterie se recharge en branchant le câble d\'alimentation.',
      },
      {
        id: 19,
        text: 'Que signifie "permissions de lecture et d\'écriture" pour un fichier ?',
        options: [
          'Les deux signifient la même chose',
          'Lecture = voir le contenu, Écriture = modifier le contenu',
          'Les deux permettent de supprimer le fichier',
          'Les deux permettent de partager le fichier en ligne',
        ],
        correct: 1,
        explanation: 'Les permissions contrôlent ce qu\'on peut faire avec un fichier. "Lecture" (Read) = voir ou ouvrir le fichier. "Écriture" (Write) = modifier, renommer ou supprimer. "Exécution" (Execute) = lancer le programme. Ces permissions protègent les fichiers système contre les modifications accidentelles.',
      },
      {
        id: 20,
        text: 'À quoi sert la défragmentation d\'un disque dur ?',
        options: [
          'À supprimer tous vos fichiers',
          'À réorganiser les données pour que le disque accède plus rapidement aux fichiers',
          'À augmenter la vitesse d\'Internet',
          'À charger les jeux vidéo instantanément',
        ],
        correct: 1,
        explanation: 'Avec le temps, les fichiers d\'un disque dur mécanique se fragmentent (éparpillent) en plusieurs morceaux. La défragmentation les rassemble pour que la tête de lecture n\'ait pas à se déplacer autant, ce qui accélère l\'accès aux fichiers. Note : les SSD n\'ont pas besoin d\'être défragmentés.',
      },
      {
        id: 21,
        text: 'Quelle est la principale différence entre Bloc-notes et un logiciel de traitement de texte ?',
        options: [
          'Aucune différence, ce sont les mêmes',
          'Bloc-notes = texte brut simple, Traitement de texte = formatage avancé',
          'Bloc-notes est plus lent',
          'Traitement de texte n\'existe pas sur ordinateur',
        ],
        correct: 1,
        explanation: 'Le Bloc-notes (Notepad) crée des fichiers texte brut (.txt) sans mise en forme : pas de gras, pas de couleur, pas d\'images. Un traitement de texte comme Word permet un formatage riche : titres, tableaux, images, styles, mise en page. Pour des documents professionnels, on utilise Word ou LibreOffice Writer.',
      },
      {
        id: 22,
        text: 'Pourquoi compresser un fichier ou un dossier en ZIP ?',
        options: [
          'Pour l\'ouvrir plus rapidement',
          'Pour prendre moins d\'espace disque et faciliter le partage',
          'Pour protéger le fichier des virus',
          'Pour le partager uniquement par e-mail',
        ],
        correct: 1,
        explanation: 'La compression ZIP réduit la taille des fichiers en encodant les données de manière plus efficace. Un dossier de 100 Mo peut devenir 60 Mo zippé. C\'est utile pour partager plusieurs fichiers en une seule archive ou pour économiser de l\'espace. Un ZIP peut aussi contenir un mot de passe pour protéger son contenu.',
      },
      {
        id: 23,
        text: 'Quelle est la différence entre mettre son ordinateur en veille et l\'arrêter complètement ?',
        options: [
          'Il n\'y a pas de différence',
          'Veille = consomme peu d\'énergie et peut redémarrer vite. Arrêt = éteint complètement',
          'La veille est plus rapide mais coûte plus cher',
          'L\'arrêt est seulement pour les ordinateurs portables',
        ],
        correct: 1,
        explanation: 'En veille, l\'ordinateur garde la RAM alimentée avec les programmes ouverts et se réveille en quelques secondes. L\'arrêt complet ferme tout, libère la mémoire et éteint tous les composants. L\'arrêt prend plus de temps au redémarrage mais est recommandé régulièrement pour appliquer les mises à jour et libérer la mémoire.',
      },
      {
        id: 24,
        text: 'Qu\'est-ce qu\'un logiciel d\'espionnage (spyware) ?',
        options: [
          'Un logiciel qui améliore votre ordinateur',
          'Un logiciel malveillant qui collecte vos données personnelles sans permission',
          'Un jeu vidéo espion',
          'Un système d\'exploitation nouveau',
        ],
        correct: 1,
        explanation: 'Un spyware est un logiciel malveillant qui s\'installe discrètement sur votre ordinateur et collecte vos informations sans votre consentement : mots de passe tapés, historique de navigation, données bancaires. Il peut arriver via des téléchargements gratuits douteux ou des publicités trompeuses.',
      },
      {
        id: 25,
        text: 'À quoi sert le raccourci clavier Alt+Tab ?',
        options: [
          'À créer une nouvelle fenêtre',
          'À basculer rapidement entre les programmes ouverts',
          'À fermer tous les programmes',
          'À sauvegarder votre travail',
        ],
        correct: 1,
        explanation: 'Alt+Tab affiche une fenêtre de sélection avec toutes les applications ouvertes. En maintenant Alt et en appuyant plusieurs fois sur Tab, vous naviguez entre les programmes. Relâchez pour ouvrir celui sélectionné. C\'est beaucoup plus rapide que de cliquer dans la barre des tâches.',
      },
      {
        id: 26,
        text: 'Dans une fenêtre de programme, qu\'indique le bouton en haut à droite avec deux carrés ?',
        options: [
          'C\'est le bouton pour fermer',
          'C\'est le bouton pour agrandir en plein écran ou redimensionner la fenêtre',
          'C\'est le bouton pour lancer une nouvelle application',
          'C\'est le bouton pour émettre du son',
        ],
        correct: 1,
        explanation: 'Les trois boutons en haut à droite d\'une fenêtre Windows sont : — (réduire dans la barre des tâches), ⬜ (agrandir en plein écran / restaurer en fenêtre), et ✕ (fermer). Le bouton avec deux carrés bascule entre mode fenêtré et plein écran.',
      },
      {
        id: 27,
        text: 'Pourquoi certaines actions sur votre ordinateur demandent un mot de passe administrateur ?',
        options: [
          'Pour ralentir votre ordinateur',
          'Pour protéger l\'ordinateur contre les modifications non autorisées',
          'Pour réduire votre productivité',
          'C\'est juste une erreur du système',
        ],
        correct: 1,
        explanation: 'Le compte administrateur a des droits élevés pour modifier le système. Windows demande une confirmation pour les actions sensibles (installer un logiciel, modifier des paramètres système) afin d\'éviter qu\'un programme malveillant ou un utilisateur non autorisé ne fasse des dommages. C\'est le principe du moindre privilège.',
      },
      {
        id: 28,
        text: 'Qu\'est-ce que le "Registre Windows" ?',
        options: [
          'Un fichier contenant vos documents',
          'Une base de données contenant toutes les configurations système, logiciels et préférences',
          'Un type de fichier image',
          'Un programme pour jouer aux jeux vidéo',
        ],
        correct: 1,
        explanation: 'Le Registre Windows est une base de données hiérarchique qui stocke les paramètres de configuration du système d\'exploitation, des logiciels installés et des préférences utilisateurs. Il est consulté en permanence par Windows. On y accède via "regedit" mais le modifier sans expertise peut endommager le système.',
      },
      {
        id: 29,
        text: 'Qu\'est-ce qu\'un fichier "sauvegarde" ou "backup" ?',
        options: [
          'Un fichier temporaire qui ralentit l\'ordinateur',
          'Une copie de vos données importantes pour les récupérer en cas de perte',
          'Un fichier qui se supprime automatiquement',
          'Un format de fichier spécial pour les jeux',
        ],
        correct: 1,
        explanation: 'Un backup est une copie de vos données stockée ailleurs (disque externe, cloud, clé USB). Si votre ordinateur tombe en panne, est volé ou infecté par un ransomware, vous pouvez récupérer vos fichiers depuis le backup. La règle 3-2-1 recommande 3 copies, sur 2 supports différents, dont 1 hors site.',
      },
      {
        id: 30,
        text: 'Qu\'est-ce que la fréquence d\'un processeur mesurée en GHz (Gigahertz) ?',
        options: [
          'La quantité de mémoire RAM de l\'ordinateur',
          'La vitesse d\'exécution des instructions du processeur',
          'Le poids de l\'ordinateur en grammes',
          'La taille de l\'écran en pouces',
        ],
        correct: 1,
        explanation: 'La fréquence en GHz indique combien de milliards d\'opérations par seconde le processeur peut effectuer. 3,5 GHz = 3,5 milliards de cycles/seconde. Plus c\'est élevé, plus le processeur est rapide pour les tâches monothread. Mais le nombre de cœurs compte aussi : un processeur 8 cœurs à 3 GHz peut être plus performant qu\'un 4 cœurs à 4 GHz.',
      },
    ],
  },

  // MODULE 1: INTERNET & GOOGLE - 5 Questions
  {
    id: 1,
    module: 'Internet & Google',
    time: null,
    description: 'Internet et moteurs de recherche (5 questions)',
    questions: [
      {
        id: 1,
        text: 'Qu\'est-ce qu\'une URL (adresse web) ?',
        options: [
          'Un type de virus informatique',
          'L\'adresse d\'une page sur Internet (exemple: www.google.com)',
          'Un fichier téléchargé sur votre ordinateur',
          'Une ligne dans un email',
        ],
        correct: 1,
        explanation: 'Une URL (Uniform Resource Locator) est l\'adresse unique d\'une ressource sur Internet. Elle contient le protocole (https://), le nom de domaine (google.com) et parfois un chemin (/search). Taper une URL dans la barre d\'adresse du navigateur vous amène directement à la page souhaitée.',
      },
      {
        id: 2,
        text: 'Comment s\'appelle le logiciel qui vous permet de consulter des pages internet ?',
        options: ['Moteur de recherche', 'Navigateur web', 'Système d\'exploitation', 'Antivirus'],
        correct: 1,
        explanation: 'Le navigateur web (Chrome, Firefox, Edge, Safari) est le logiciel qui lit et affiche les pages web. Le moteur de recherche (Google, Bing) est un service accessible via le navigateur qui indexe et retrouve des pages. Le navigateur est l\'outil, le moteur de recherche est un service qu\'on utilise dedans.',
      },
      {
        id: 3,
        text: 'Vous cherchez des informations en français. Lequel utiliseriez-vous ?',
        options: [
          'Google Africa (n\'existe pas officiellement)',
          'Google.com avec la langue définie en français ou Google.ci pour Côte d\'Ivoire',
          'Yahoo du Sénégal',
          'Bing uniquement pour l\'Afrique',
        ],
        correct: 1,
        explanation: 'Google propose des versions localisées par pays (google.ci pour Côte d\'Ivoire, google.sn pour Sénégal, google.fr pour France) et permet de définir la langue des résultats. "Google Africa" n\'est pas un domaine officiel. Pour des recherches en contexte africain francophone, google.ci ou google.fr avec la bonne langue sont les meilleurs choix.',
      },
      {
        id: 4,
        text: 'Que veut dire "HTTPS" dans une URL ?',
        options: [
          'C\'est plus rapide que HTTP',
          'C\'est une version ancienne d\'Internet',
          'La connexion est chiffrée et sécurisée',
          'C\'est un fournisseur d\'accès Internet',
        ],
        correct: 2,
        explanation: 'HTTPS (HyperText Transfer Protocol Secure) signifie que les données échangées entre votre navigateur et le serveur sont chiffrées via SSL/TLS. Personne ne peut intercepter vos mots de passe ou données bancaires. Le cadenas vert dans la barre d\'adresse indique une connexion HTTPS. Évitez de saisir des données sensibles sur des sites HTTP.',
      },
      {
        id: 5,
        text: 'Vous trouvez une information sur Internet qui semble incroyable. Comment vérifier sa crédibilité ?',
        options: [
          'Vous la partagez immédiatement sur le réseau social',
          'Vous vérifiez la source, cherchez d\'autres sources fiables, analysez les dates',
          'Vous acceptez tout ce que vous lisez',
          'Vous demandez simplement à vos amis sur WhatsApp',
        ],
        correct: 1,
        explanation: 'Face aux fake news, appliquez la méthode SIFT : Stop (ne réagissez pas immédiatement), Investigate the source (qui publie ?), Find better coverage (d\'autres sources confirment-elles ?), Trace claims (remonter à la source originale). Vérifiez la date de publication — une vieille info peut sembler nouvelle si elle est repartagée.',
      },
    ],
  },

  // MODULE 2: EMAIL - 5 Questions
  {
    id: 2,
    module: 'Email',
    time: null,
    description: 'Communication par email (5 questions)',
    questions: [
      {
        id: 1,
        text: 'Quelle est la structure correcte d\'une adresse email ?',
        options: ['nom.domaine@com', 'nom@domaine.extension', '@nomdiffrandomdom', 'domaine.nom@'],
        correct: 1,
        explanation: 'Une adresse email a toujours la forme : identifiant@domaine.extension. Exemple : jean.dupont@gmail.com. La partie avant @ identifie l\'utilisateur, la partie après est le service email (domaine + extension). L\'@ est obligatoire et unique dans chaque adresse.',
      },
      {
        id: 2,
        text: 'Que signifie "CC" dans un email ?',
        options: [
          'Confidentiel Crypté',
          'Copie Conforme (copie visible de l\'email)',
          'Confirmation de Compte',
          'Code de Connexion',
        ],
        correct: 1,
        explanation: 'CC (Copie Conforme) permet d\'envoyer une copie de l\'email à des personnes en infos, sans qu\'elles soient les destinataires principaux. Tous les destinataires voient les adresses en CC. BCC (Copie Cachée) fait pareil mais en masquant les adresses aux autres. CC s\'utilise pour tenir quelqu\'un informé sans lui demander d\'agir.',
      },
      {
        id: 3,
        text: 'Vous recevez un email vous demandant de "vérifier votre compte PayPal en cliquant ici". Quelle est la bonne action ?',
        options: [
          'Cliquer sur le lien fourni',
          'Répondre avec votre mot de passe',
          'Aller directement sur PayPal.com sans cliquer le lien',
          'Partager l\'email avec vos amis',
        ],
        correct: 2,
        explanation: 'C\'est du phishing — une arnaque classique qui imite un email officiel pour voler vos identifiants. La règle d\'or : ne jamais cliquer sur les liens dans les emails suspects. Ouvrez toujours votre navigateur et tapez vous-même l\'adresse du site (paypal.com). Un vrai service ne vous demandera jamais votre mot de passe par email.',
      },
      {
        id: 4,
        text: 'En Afrique, pour envoyer de l\'argent par email, lequel utiliseriez-vous ?',
        options: [
          'L\'email standard Gmail',
          'Un service de paiement mobile africain (Orange Money, MTN Mobile Money, Wave)',
          'Yahoo Mail pour envoyer de l\'argent',
          'Aucun, cela n\'existe pas',
        ],
        correct: 1,
        explanation: 'L\'email ne permet pas d\'envoyer de l\'argent directement. En Afrique, les services de Mobile Money sont très développés : Orange Money, MTN Mobile Money, Wave, Moov Money. Ces plateformes permettent des transferts rapides, même sans compte bancaire, via son numéro de téléphone.',
      },
      {
        id: 5,
        text: 'Vous devez envoyer un document confidentiel par email à votre patron. Que faites-vous ?',
        options: [
          'Vous l\'envoyez en clair (lisible directement)',
          'Vous chiffrez le PDF avec un mot de passe et l\'envoyez séparément du mot de passe',
          'Vous ne l\'envoyez pas du tout',
          'Vous le postez sur votre compte Facebook',
        ],
        correct: 1,
        explanation: 'Pour sécuriser un document confidentiel, chiffrez-le avec un mot de passe (possible avec Adobe Acrobat, LibreOffice, ou en créant un ZIP protégé). Envoyez le fichier par email et le mot de passe via un autre canal (SMS, appel). Ainsi, même si l\'email est intercepté, le document reste illisible.',
      },
    ],
  },

  // MODULE 3: BUREAUTIQUE - 5 Questions
  {
    id: 3,
    module: 'Bureautique',
    time: null,
    description: 'Outils bureautiques (5 questions)',
    questions: [
      {
        id: 1,
        text: 'Quel logiciel utilise-t-on pour créer un document texte ?',
        options: ['Microsoft Excel', 'Microsoft Word ou LibreOffice Writer', 'Microsoft PowerPoint', 'Adobe Photoshop'],
        correct: 1,
        explanation: 'Microsoft Word et LibreOffice Writer sont des logiciels de traitement de texte, conçus pour créer des documents (lettres, CV, rapports). Excel sert aux calculs et tableurs, PowerPoint aux présentations, Photoshop à la retouche d\'images. LibreOffice est une alternative gratuite à Microsoft Office.',
      },
      {
        id: 2,
        text: 'Pour faire des calculs et des graphiques, quel logiciel utilisez-vous ?',
        options: ['Word', 'PowerPoint', 'Excel ou LibreOffice Calc', 'Notepad'],
        correct: 2,
        explanation: 'Excel (Microsoft) et Calc (LibreOffice) sont des tableurs : ils permettent de créer des tableaux avec des formules automatiques (somme, moyenne, pourcentage), des graphiques (barres, camembert) et des bases de données simples. Indispensables pour les budgets, inventaires et analyses de données.',
      },
      {
        id: 3,
        text: 'En Afrique, vous devez créer un budget pour un petit commerce. Quel outil est le mieux ?',
        options: [
          'Vous notez en papier',
          'Un tableur (Excel ou Calc) avec des catégories, des calculs automatiques',
          'Google Docs (document texte)',
          'Un email',
        ],
        correct: 1,
        explanation: 'Un tableur est idéal pour un budget commercial : vous listez vos revenus et dépenses en colonnes, les formules calculent automatiquement totaux et marges, et les graphiques visualisent les tendances. Google Sheets (gratuit, en ligne) est une excellente alternative accessible même sur téléphone.',
      },
      {
        id: 4,
        text: 'Comment insérer une image dans un document Word ?',
        options: [
          'Vous ne pouvez pas',
          'Insertion > Image > Sélectionner le fichier',
          'Vous devez payer pour ça',
          'Ce n\'est possible qu\'en version en ligne',
        ],
        correct: 1,
        explanation: 'Dans Word, allez dans l\'onglet "Insertion" puis cliquez sur "Image". Vous pouvez insérer une image depuis votre ordinateur, depuis Internet (via "Images en ligne") ou copier-coller directement une image. Vous pouvez ensuite redimensionner et positionner l\'image dans le document.',
      },
      {
        id: 5,
        text: 'Vous devez formater un CV professionnel. Que ne faites-vous PAS ?',
        options: [
          'Ajouter des couleurs sobres',
          'Utiliser des polices lisibles',
          'Avec un design complètement fou et de la Comic Sans',
          'Garder une structure claire',
        ],
        correct: 2,
        explanation: 'Un CV professionnel doit être sobre, lisible et structuré. Évitez Comic Sans (police non professionnelle), les couleurs criardes, trop d\'ornements. Préférez des polices sérieuses (Calibri, Arial, Times New Roman), une structure claire (expériences, formation, compétences), et des couleurs discrètes si vous en utilisez.',
      },
    ],
  },

  // MODULE 4: CYBERSÉCURITÉ - 5 Questions
  {
    id: 4,
    module: 'Cybersécurité',
    time: null,
    description: 'Protection et sécurité informatique (5 questions)',
    questions: [
      {
        id: 1,
        text: 'Un mot de passe sûr doit contenir :',
        options: [
          'Uniquement votre nom',
          'Uniquement des chiffres',
          'Lettres (majuscules + minuscules) + chiffres + caractères spéciaux',
          'Votre date de naissance',
        ],
        correct: 2,
        explanation: 'Un bon mot de passe combine majuscules, minuscules, chiffres et symboles (@, #, !...) et fait au moins 12 caractères. Évitez les informations personnelles (nom, date de naissance) car elles sont faciles à deviner. Utilisez un gestionnaire de mots de passe (Bitwarden, 1Password) pour en générer et mémoriser des forts.',
      },
      {
        id: 2,
        text: 'Que signifie "malware" ?',
        options: [
          'Un logiciel utile',
          'Un virus ou logiciel malveillant',
          'Un système d\'exploitation',
          'Un type de processeur',
        ],
        correct: 1,
        explanation: 'Malware (malicious software) désigne tout logiciel conçu pour nuire : virus (se réplique), ransomware (chiffre vos fichiers et demande une rançon), trojan (ouvre une porte dérobée), spyware (espionne). La protection passe par un antivirus à jour, les mises à jour système et la vigilance face aux téléchargements.',
      },
      {
        id: 3,
        text: 'Vous utilisez le WiFi public d\'un café en Afrique. Comment protégez-vous vos données ?',
        options: [
          'Vous faites vos transactions bancaires directement',
          'Vous utilisez un VPN pour chiffrer votre connexion',
          'Vous ignorez la sécurité',
          'Vous utilisez Facebook uniquement',
        ],
        correct: 1,
        explanation: 'Le WiFi public est non sécurisé — quelqu\'un sur le même réseau peut intercepter vos données non chiffrées. Un VPN (Virtual Private Network) chiffre tout votre trafic, rendant vos données illisibles même si interceptées. Évitez aussi les transactions bancaires sur WiFi public, même avec VPN.',
      },
      {
        id: 4,
        text: 'Un virus peut se propager par :',
        options: [
          'L\'air',
          'Les emails avec pièces jointes malveillantes',
          'Juste en regardant votre écran',
          'Les livres',
        ],
        correct: 1,
        explanation: 'Les virus informatiques se propagent via : pièces jointes d\'emails malveillants, clés USB infectées, téléchargements depuis des sites douteux, logiciels piratés, et parfois en visitant des sites web compromis (drive-by download). Ils ne peuvent pas se transmettre par l\'air ou le simple regard — c\'est uniquement numérique.',
      },
      {
        id: 5,
        text: 'Après un achat en ligne, vous recevez un SMS "Cliquez pour confirmer votre livraison". C\'est quoi ?',
        options: [
          'Un vrai message de livraison',
          'Une tentative de vol d\'identité (smishing) - ne cliquez pas',
          'Un service premium à acheter',
          'Un message de votre banque',
        ],
        correct: 1,
        explanation: 'C\'est du smishing (SMS phishing) — une technique d\'arnaque très répandue en Afrique. Le lien vous amène sur un faux site qui vole vos coordonnées bancaires ou installe un malware. Vérifiez toujours directement sur le site officiel du transporteur en tapant l\'adresse vous-même. Les vrais livreurs ne demandent jamais vos données par SMS.',
      },
    ],
  },

  // MODULE 5: INTELLIGENCE ARTIFICIELLE - 5 Questions
  {
    id: 5,
    module: 'Intelligence Artificielle',
    time: null,
    description: 'IA et technologies intelligentes (5 questions)',
    questions: [
      {
        id: 1,
        text: 'Qu\'est-ce que l\'Intelligence Artificielle (IA) ?',
        options: [
          'Un film de science-fiction',
          'Un ensemble de technologies imitant l\'intelligence humaine',
          'Un virus informatique',
          'Un navigateur Internet',
        ],
        correct: 1,
        explanation: 'L\'IA est un ensemble de techniques permettant aux machines de simuler des capacités humaines : apprendre (machine learning), comprendre le langage (NLP), reconnaître des images (vision par ordinateur), prendre des décisions. Elle est déjà présente partout : recommandations Netflix, traduction Google, assistants vocaux, reconnaissance faciale.',
      },
      {
        id: 2,
        text: 'ChatGPT est :',
        options: [
          'Un email gratuit',
          'Un modèle de langage IA pour converser',
          'Un jeu vidéo',
          'Un fournisseur d\'accès Internet',
        ],
        correct: 1,
        explanation: 'ChatGPT est un modèle de langage (LLM - Large Language Model) développé par OpenAI. Il peut répondre à des questions, rédiger des textes, expliquer des concepts, coder et bien plus. Il est entraîné sur d\'immenses quantités de texte. Des alternatives existent : Claude (Anthropic), Gemini (Google), Mistral (France).',
      },
      {
        id: 3,
        text: 'En Afrique, une petite entreprise peut utiliser l\'IA pour :',
        options: [
          'Remplacer tous les employés (mauvaise idée !)',
          'Améliorer le service client (chatbot), analyse de données, recommandations',
          'Rien, c\'est trop compliqué',
          'Juste pour faire du marketing',
        ],
        correct: 1,
        explanation: 'L\'IA offre des opportunités concrètes pour les PME africaines : chatbots WhatsApp pour le service client 24h/24, analyse des ventes pour identifier les tendances, traduction automatique pour atteindre plusieurs langues, génération de contenu marketing. Des outils comme Canva AI, ChatGPT, ou Google Analytics sont accessibles gratuitement.',
      },
      {
        id: 4,
        text: 'L\'IA générative peut créer :',
        options: ['Que du texte', 'Texte, images, vidéos, code, musique', 'Rien', 'Que des images'],
        correct: 1,
        explanation: 'L\'IA générative crée du nouveau contenu : texte (ChatGPT, Claude), images (DALL-E, Midjourney, Stable Diffusion), vidéos (Sora, Runway), code (GitHub Copilot), musique (Suno, Udio), voix synthétiques. C\'est une révolution créative, mais elle pose des questions sur les droits d\'auteur et la désinformation (deepfakes).',
      },
      {
        id: 5,
        text: 'Quels sont les risques éthiques de l\'IA ?',
        options: [
          'Pas de risques',
          'Biais dans les algorithmes, atteinte à la vie privée, deepfakes, dépendance',
          'Aucun risque techniquement',
          'Juste un hype sans importance',
        ],
        correct: 1,
        explanation: 'L\'IA présente des risques réels : biais algorithmiques (discrimination dans le recrutement ou les prêts), atteinte à la vie privée (reconnaissance faciale de masse), deepfakes (vidéos truquées pour la désinformation), perte d\'emplois dans certains secteurs, et risques de cybersécurité. Une régulation comme l\'AI Act européen tente d\'encadrer ces usages.',
      },
    ],
  },

  // MODULE 6: EMPLOYABILITÉ - 5 Questions
  {
    id: 6,
    module: 'Employabilité',
    time: null,
    description: 'Emploi et développement de carrière (5 questions)',
    questions: [
      {
        id: 1,
        text: 'Pour chercher un emploi en ligne, le premier outil est :',
        options: [
          'Facebook',
          'LinkedIn ou les jobboards locaux africains',
          'Appel téléphonique',
          'Votre CV papier',
        ],
        correct: 1,
        explanation: 'LinkedIn est le réseau professionnel mondial numéro 1 avec 900M+ membres. En Afrique, des plateformes locales complètent l\'offre : Jobberman (Nigeria, Ghana), Emploi.ci (Côte d\'Ivoire), Rekrute (Maroc), Africa Jobs. Créez un profil LinkedIn complet avec photo, expériences et compétences — beaucoup de recruteurs y cherchent directement des candidats.',
      },
      {
        id: 2,
        text: 'Qu\'est-ce qu\'un portfolio numérique ?',
        options: [
          'Un dossier papier',
          'Une collection de vos projets, compétences, résultats en ligne',
          'Une formation payante',
          'Un CV Word classique',
        ],
        correct: 1,
        explanation: 'Un portfolio numérique est un site web (ou page en ligne) qui présente vos réalisations concrètes : projets réalisés, textes écrits, designs créés, code développé. Contrairement au CV qui liste ce que vous savez faire, le portfolio prouve ce que vous avez fait. Des outils gratuits : Notion, GitHub Pages, Wix, Behance (design).',
      },
      {
        id: 3,
        text: 'En Afrique, quel est l\'avantage d\'avoir des certifications numériques ?',
        options: [
          'Aucun intérêt',
          'Différenciation face aux concurrents, preuve de compétences vérifiées',
          'Uniquement pour les riches',
          'Juste pour décorer votre CV',
        ],
        correct: 1,
        explanation: 'Dans un marché du travail africain en forte croissance numérique, les certifications attestent de compétences réelles vérifiables. Elles compensent parfois le manque de diplômes formels, permettent de postuler à des offres internationales en remote, et renforcent la crédibilité auprès des employeurs. Les certifications Google, Microsoft, et Syllabix sont reconnues.',
      },
      {
        id: 4,
        text: 'Le networking numérique signifie :',
        options: [
          'Acheter des ordinateurs',
          'Créer des contacts professionnels en ligne (LinkedIn, events virtuels)',
          'Installer un réseau WiFi',
          'Aucun rapport avec l\'emploi',
        ],
        correct: 1,
        explanation: 'Le networking professionnel en ligne consiste à construire un réseau de contacts dans votre domaine : suivre des professionnels sur LinkedIn, commenter leurs publications, participer à des groupes thématiques, assister à des webinaires, rejoindre des communautés Slack ou Discord. 70-80% des emplois sont pourvus via le réseau, pas par annonces publiques.',
      },
      {
        id: 5,
        text: 'Quel est le meilleur stratégie pour une carrière tech durable en Afrique ?',
        options: [
          'Acquérir une compétence et rester statique',
          'Apprendre continuellement, réseauter, avoir un portfolio visible, être flexible',
          'Attendre une opportunité',
          'Copier exactement ce que les autres font',
        ],
        correct: 1,
        explanation: 'Le secteur tech évolue très rapidement. Les compétences d\'aujourd\'hui peuvent devenir obsolètes dans 5 ans. La stratégie gagnante combine : apprentissage continu (nouvelles technologies, certifications), réseau professionnel actif (LinkedIn, événements), portfolio visible de réalisations concrètes, et flexibilité pour s\'adapter aux évolutions du marché africain et mondial.',
      },
    ],
  },
];
